[tool.poetry]
name = "Sparkles"
version = "]"
description = ""
authors = ["QamarJaradat <moon19.qs@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
