# Generated by Django 3.1.4 on 2020-12-03 13:44

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('tip_id', djongo.models.fields.ObjectIdField(
                    auto_created=True, primary_key=True, serialize=False)),
                ('tip_title', models.CharField(max_length=40)),
                ('tip_text', models.TextField()),
                ('tip_img', models.TextField()),
                ('user_id', models.TextField()),
            ],
        ),
    ]
