# Generated by Django 3.1.4 on 2020-12-05 13:09

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('fav_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('tip_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipCommints',
            fields=[
                ('commint_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('tip_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('commint_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('tip_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('tip_title', models.CharField(max_length=40)),
                ('tip_text', models.TextField()),
                ('tip_img', models.TextField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
