# Generated by Django 3.1.4 on 2020-12-09 14:24

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('admin_name', models.TextField()),
                ('admin_email', models.TextField()),
                ('admin_password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('tip_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=40)),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_type', models.BooleanField()),
                ('product_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('service_name', models.TextField()),
                ('service_img', models.TextField()),
                ('service_price', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('tip_title', models.CharField(max_length=40)),
                ('tip_text', models.TextField()),
                ('tip_img', models.TextField()),
                ('user_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipCommints',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('tip_id', models.IntegerField()),
                ('commint_text', models.TextField()),
                ('user_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProducts',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('product_id', models.TextField()),
                ('user_product_location', models.TextField()),
                ('user_product_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('user_email', models.TextField()),
                ('user_password', models.TextField()),
                ('user_phon', models.TextField()),
                ('user_img', models.TextField()),
                ('user_bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('service_id', models.TextField()),
                ('user_service_location', models.TextField()),
                ('user_service_date', models.DateField()),
                ('user_service_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTips',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('tip_id', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tips',
        ),
    ]
