# Generated by Django 3.0.5 on 2020-12-07 18:50

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('admin_name', models.TextField()),
                ('admin_email', models.TextField()),
                ('admin_password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('fav_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('tip_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=40)),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_type', models.BooleanField()),
                ('product_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('service_name', models.TextField()),
                ('service_img', models.TextField()),
                ('service_price', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipCommints',
            fields=[
                ('commint_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('tip_id', models.TextField()),
                ('user_id', models.TextField()),
                ('commint_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProducts',
            fields=[
                ('user_product_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('product_id', models.TextField()),
                ('user_product_location', models.TextField()),
                ('user_product_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('user_email', models.TextField()),
                ('user_password', models.TextField()),
                ('user_phon', models.TextField()),
                ('user_img', models.TextField()),
                ('user_bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('user_service_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('service_id', models.TextField()),
                ('user_service_location', models.TextField()),
                ('user_service_date', models.DateField()),
                ('user_service_hours', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Tips',
            new_name='Tip',
        ),
        migrations.RenameField(
            model_name='tip',
            old_name='tip_id',
            new_name='_id',
        ),
    ]
