# Generated by Django 3.1.4 on 2020-12-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fEnd', '0002_auto_20201207_1850'),
        ('fEnd', '0002_auto_20201207_1144'),
    ]

    operations = [
    ]
